# Generated by Django 6.0.7 on 2026-08-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('playtime', models.DateTimeField(verbose_name='date_published')),
                ('training', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
