# Generated by Django 6.0.7 on 2026-08-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
