# Generated by Django 6.0.7 on 2026-08-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_sport_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
