# Generated by Django 6.0.7 on 2026-08-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('costly', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
