# Generated by Django 6.0.7 on 2026-08-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('married', models.BooleanField(default='Unmarried')),
            ],
        ),
        migrations.DeleteModel(
            name='players',
        ),
        migrations.DeleteModel(
            name='teams',
        ),
    ]
